# Generated by Django 5.1.3 on 2025-06-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_telegramorder_delete_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramorder',
            old_name='user_id',
            new_name='telegram_user_id',
        ),
        migrations.RemoveField(
            model_name='telegramorder',
            name='username',
        ),
        migrations.AddField(
            model_name='telegramorder',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
