# Generated by Django 5.1.3 on 2025-06-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_product_category_remove_product_created_at_and_more'),
        ('orders', '0006_telegramorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramorder',
            old_name='telegram_user_id',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='telegramorder',
            name='address',
        ),
        migrations.RemoveField(
            model_name='telegramorder',
            name='telegram_username',
        ),
        migrations.AddField(
            model_name='telegramorder',
            name='delivery_address',
            field=models.CharField(default='Без адреса', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramorder',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('in_progress', 'В обработке'), ('completed', 'Выполнен'), ('cancelled', 'Отменён')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='telegramorder',
            name='username',
            field=models.CharField(default='Без адреса', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='catalog.product'),
        ),
    ]
